name: TechTestApp
options:
  bundleIdPrefix: com.techtestapp
  deploymentTarget:
    iOS: 13.7
packages:
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.2.0
  RxDataSources:
    url: https://github.com/RxSwiftCommunity/RxDataSources.git
    from: 5.0.0
  SDWebImage:
    url: https://github.com/SDWebImage/SDWebImage.git
    from: 5.12.1
targets:
  TechTestApp:
    type: application
    platform: iOS
    sources: [TechTestApp]
    dependencies:
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxDataSources
      - package: SDWebImage
    preBuildScripts:
      - path: Scripts/Build-Swiftlint-Scan.sh
        name: Swiftlint Scan
    settings:
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      VERSIONING_SYSTEM: "apple-generic"
      SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
      TARGETED_DEVICE_FAMILY: 1,2
  TechTestAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: [TechTestAppTests]
    dependencies:
      - target: TechTestApp
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxTest

schemes:
  TechTestApp:
    build:
      targets:
        TechTestApp: all
    test:
      gatherCoverageData: true
      targets:
        - name: TechTestAppTests
          parallelizable: true
          randomExecutionOrder: true      